
package sinec;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import static sinec.Sinec.generar;
//import static sinec.Sinec.numero;

/**
 *
 * @author Gio
 */
public class Homes extends javax.swing.JFrame {
   public static String[] serie=new String[20]; 
   public static int cont=0;
   public static String rutaFile="";
    /**
     * Creates new form Homes
     */
    public Homes() {
        initComponents();
         
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel11 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Panel14 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Panel9 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Panel15 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        Panel17 = new javax.swing.JTextField();
        Panel19 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Panel6 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        Panel20 = new javax.swing.JTextField();
        Panel13 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        Panel4 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Panel3 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Panel2 = new javax.swing.JTextField();
        Panel7 = new javax.swing.JTextField();
        Panel8 = new javax.swing.JTextField();
        Panel1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        Panel5 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        Panel10 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        Panel16 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        Panel18 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        Panel12 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ruta = new javax.swing.JTextField();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel11KeyReleased(evt);
            }
        });
        getContentPane().add(Panel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 160, -1));

        jLabel41.setText("Panel 20");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, -1, -1));

        jLabel25.setText("Panel 13");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        Panel14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel14KeyReleased(evt);
            }
        });
        getContentPane().add(Panel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 160, -1));

        jLabel36.setText("Panel 19");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        jLabel31.setText("Panel 14");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        Panel9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel9KeyReleased(evt);
            }
        });
        getContentPane().add(Panel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 160, -1));

        jLabel26.setText("Panel 10");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        Panel15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel15KeyReleased(evt);
            }
        });
        getContentPane().add(Panel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 160, -1));

        jLabel37.setText("Panel 4");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 50, -1, -1));

        Panel17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel17KeyReleased(evt);
            }
        });
        getContentPane().add(Panel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 160, -1));

        Panel19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel19KeyReleased(evt);
            }
        });
        getContentPane().add(Panel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 160, -1));

        jLabel27.setText("Panel 6");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        Panel6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel6KeyReleased(evt);
            }
        });
        getContentPane().add(Panel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 160, -1));

        jLabel38.setText("Panel 8");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, -1, -1));

        Panel20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel20KeyReleased(evt);
            }
        });
        getContentPane().add(Panel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 320, 160, -1));

        Panel13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel13KeyReleased(evt);
            }
        });
        getContentPane().add(Panel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 160, -1));

        jLabel33.setText("Panel 7");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        Panel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel4KeyReleased(evt);
            }
        });
        getContentPane().add(Panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 50, 160, -1));

        jLabel22.setText("Panel 1");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 54, -1, -1));

        jLabel28.setText("Panel 2");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        Panel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel3KeyReleased(evt);
            }
        });
        getContentPane().add(Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 160, -1));

        jLabel39.setText("Panel 12");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 190, -1, -1));

        jLabel23.setText("Panel 5");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        Panel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel2KeyReleased(evt);
            }
        });
        getContentPane().add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 160, -1));

        Panel7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel7KeyReleased(evt);
            }
        });
        getContentPane().add(Panel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 160, -1));

        Panel8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel8KeyReleased(evt);
            }
        });
        getContentPane().add(Panel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, 160, -1));

        Panel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel1KeyReleased(evt);
            }
        });
        getContentPane().add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 160, -1));

        jLabel29.setText("Panel 17");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel34.setText("Panel 11");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, -1, -1));

        Panel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel5KeyReleased(evt);
            }
        });
        getContentPane().add(Panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 160, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Bar scanner");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 96, -1));

        Panel10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel10KeyReleased(evt);
            }
        });
        getContentPane().add(Panel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 160, -1));

        jLabel32.setText("Panel 3");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        Panel16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel16KeyReleased(evt);
            }
        });
        getContentPane().add(Panel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, 160, -1));

        jLabel40.setText("Panel 16");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, -1, -1));

        Panel18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel18KeyReleased(evt);
            }
        });
        getContentPane().add(Panel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 160, -1));

        jLabel35.setText("Panel 15");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, -1));

        Panel12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Panel12KeyReleased(evt);
            }
        });
        getContentPane().add(Panel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 180, 160, -1));

        jLabel24.setText("Panel 9");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel30.setText("Panel 18");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        jLabel1.setText("IT CROWT SINEC    BarScanner v1.0");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        ruta.setText("C:\\xml");
        ruta.setToolTipText("");
        getContentPane().add(ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, 180, -1));

        label1.setText("Ruta");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Panel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel1KeyReleased
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel1.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel2.requestFocus();
            
        }
    }//GEN-LAST:event_Panel1KeyReleased

    private void Panel2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel2KeyReleased
              if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel2.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel3.requestFocus();
        }
    }//GEN-LAST:event_Panel2KeyReleased

    private void Panel3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel3KeyReleased
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel3.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel4.requestFocus();
        }
    }//GEN-LAST:event_Panel3KeyReleased

    private void Panel4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel4KeyReleased
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel4.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel5.requestFocus();
        }
    }//GEN-LAST:event_Panel4KeyReleased

    private void Panel5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel5KeyReleased
       if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel5.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel6.requestFocus();
        }
    }//GEN-LAST:event_Panel5KeyReleased

    private void Panel6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel6KeyReleased
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel6.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel7.requestFocus();
        }
    }//GEN-LAST:event_Panel6KeyReleased

    private void Panel7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel7KeyReleased
       if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel7.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel8.requestFocus();
        }
    }//GEN-LAST:event_Panel7KeyReleased

    private void Panel8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel8KeyReleased
         if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel8.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel9.requestFocus();
        }
    }//GEN-LAST:event_Panel8KeyReleased

    private void Panel9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel9KeyReleased
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel9.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel10.requestFocus();
        }
    }//GEN-LAST:event_Panel9KeyReleased

    private void Panel10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel10KeyReleased
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel10.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel11.requestFocus();
        }
    }//GEN-LAST:event_Panel10KeyReleased

    private void Panel11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel11KeyReleased
         if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel11.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel12.requestFocus();
        }
    }//GEN-LAST:event_Panel11KeyReleased

    private void Panel12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel12KeyReleased
         if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel12.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel13.requestFocus();
        }
    }//GEN-LAST:event_Panel12KeyReleased

    private void Panel13KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel13KeyReleased
         if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel13.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel14.requestFocus();
        }
    }//GEN-LAST:event_Panel13KeyReleased

    private void Panel14KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel14KeyReleased
         if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel14.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel15.requestFocus();
        }
    }//GEN-LAST:event_Panel14KeyReleased

    private void Panel15KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel15KeyReleased
         if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel15.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel16.requestFocus();
        }
    }//GEN-LAST:event_Panel15KeyReleased

    private void Panel16KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel16KeyReleased
         if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel16.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel17.requestFocus();
        }
    }//GEN-LAST:event_Panel16KeyReleased

    private void Panel17KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel17KeyReleased
                 if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel17.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel18.requestFocus();
        }
    }//GEN-LAST:event_Panel17KeyReleased

    private void Panel18KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel18KeyReleased
                if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel18.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel19.requestFocus();
        }
    }//GEN-LAST:event_Panel18KeyReleased

    private void Panel19KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel19KeyReleased
            if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel19.getText();
            System.out.println(serie[cont]);
            cont++;
            Panel20.requestFocus();
        }
    }//GEN-LAST:event_Panel19KeyReleased

    private void Panel20KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Panel20KeyReleased
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            serie[cont]=Panel19.getText();
            System.out.println(serie[cont]);
            cont++;
            if (cont==20){
                try {
                  rutaFile=ruta.getText();
                  generar();  
                } catch (Exception e) {
                }
                    
                Panel1.setText(""); 
                Panel2.setText("");
                Panel3.setText("");
                Panel3.setText("");
                Panel4.setText("");
                Panel5.setText("");
                
                Panel6.setText("");
                Panel7.setText("");
                Panel8.setText("");
                Panel9.setText("");
                Panel10.setText("");
                
                Panel11.setText("");
                Panel12.setText("");
                Panel13.setText("");
                Panel14.setText("");
                Panel15.setText("");
                
                Panel16.setText("");
                Panel17.setText("");
                Panel18.setText("");
                Panel19.setText("");
                Panel20.setText("");
                cont=0;
                Panel1.requestFocus();
                
               // JOptionPane.showConfirmDialog(rootPane,"FILE saved");
            }
            
        }
    }//GEN-LAST:event_Panel20KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homes().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Panel1;
    private javax.swing.JTextField Panel10;
    private javax.swing.JTextField Panel11;
    private javax.swing.JTextField Panel12;
    private javax.swing.JTextField Panel13;
    private javax.swing.JTextField Panel14;
    private javax.swing.JTextField Panel15;
    private javax.swing.JTextField Panel16;
    private javax.swing.JTextField Panel17;
    private javax.swing.JTextField Panel18;
    private javax.swing.JTextField Panel19;
    private javax.swing.JTextField Panel2;
    private javax.swing.JTextField Panel20;
    private javax.swing.JTextField Panel3;
    private javax.swing.JTextField Panel4;
    private javax.swing.JTextField Panel5;
    private javax.swing.JTextField Panel6;
    private javax.swing.JTextField Panel7;
    private javax.swing.JTextField Panel8;
    private javax.swing.JTextField Panel9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private java.awt.Label label1;
    private javax.swing.JTextField ruta;
    // End of variables declaration//GEN-END:variables


}
